parameters:
  dataset : 'Yu_2022' # Name of dataset you want to show on the metadata table
input:
  path_to_accessions : '../data/accessions.txt' # Path to a txt file that records a list of sample accessions

output:
  output_directory : '../data/metadata/Yu_2022/'
